### ISSUE TITLE
question about av2 2d

### ISSUE THREAD

**Issue by www04576** [HXMap/MapQR#7]
Thank you very much for your work.
I see that you have provided config files for 2D and 3D of the av2 dataset, and they have the following differences:
`z_cfg = dict(pred_z_flag=True, gt_z_flag=True,)`
`code_size=3,`
`pt_dim=3,`
`data_root = 'data_bak/argoverse2/sensor/'`
Is that all the difference between them? Is there a difference in the `.pkl` data they use?
I was able to run it successfully with the `av2_3d` config file, but the `Map` I trained with the `av2_2d` config file was 0.000.
Looking forward to your reply. Thank you.

**Comment by fishmarch** [comment]
Oh, it's a mistake for the data_root, I have corrected it. There is no difference in .pkl file for 2d and 3d config, but you need to make sure the file is generated as in MapTRv2.

Are you using our latest codes? There is a mistake in the original MapTRv2 for training 2d config, we have corrected in our latest codes, please check here:
https://github.com/HXMap/MapQR/blob/058768e60a424c8e6439209f74ccfd535237a5ff/projects/mmdet3d_plugin/datasets/map_utils/mean_ap.py#L128-L130

**Comment by www04576** [comment]
Thank you so much for fixing this mistake. It works for me.
Best wishes!

**Comment by yutong-yang-mb** [comment]
Hi, I have a similar issue regarding the eval of MapQR trained on Av2 dataset.

- I used the dataset preparation script to obtain the av2 dataset annotations; my av2 version is 0.2.1
- I used the provided 2d av2 config and the trained model in this repo; 
- I failed to evaluate the model due to the following errors

`File "/root/projects/mmdet3d_plugin/datasets/map_utils/mean_ap.py", line 129, in get_cls_results
    sampled_points = np.array([list(line.interpolate(distance).coords) for distance in distances]).reshape(-1, dataset_code_size)
ValueError: cannot reshape array of size 200 into shape (3)`

I would very appreciate if you could provide
- what av2 version has been used in this repo?
- Do you have any suggestion about the above issue?

Thank you very much! ^_^ @fishmarch @www04576

**Comment by yutong-yang-mb** [comment]
hi, any feedbacks regarding above mentioned issue? Thanks! @fishmarch

**Comment by fishmarch** [comment]
> hi, any feedbacks regarding above mentioned issue? Thanks! [@fishmarch](https://github.com/fishmarch)

Hi, I haven't looked at this part of codes for a long time, so it's hard for me to tell you exactly how to fix it. But I can tell the reason for this kind of error. You need to check the dimension of your gts extracted from the original dataset. In your errors, it seems dataset_code_size is 3, but the lines from your data has only (x, y) two dimensions. You can set dataset_code_size be 2, or generate 3D gts.

**Comment by yutong-yang-mb** [comment]
Hi, thanks for your suggestions! I tried it again. but still the same issue, donno why the dims in my gts are 2d so they can not fit into 3-dim dataset_code_size (as the error shows). I donno if this has anything to do with the av2 library version. Could you please provide the generated pkl files for the av2 datasets so I can quickly test my av2 data? The data is stoarged in cloud and I wanna to check if the data has been modified by others who also have access to the data. THank you in advance! @fishmarch
